#!/bin/bash

# hx-comm-lang: getting the extension of the edited file in Helix

comm_file="${HX_COMM_DIR}/comm-lang"
[[ "$PWD" != "$HOME" ]] && recur="-r"
modified_file=$(inotifywait $recur -qe modify --format '%f' "$PWD")
echo "${modified_file##*.}" > "$comm_file"
