#!/bin/bash

# hx-comm-lang: getting the extension of the edited file in Helix

commfile="${HX_COMM_DIR}/comm-lang"

if [[ "$PWD" != "$HOME" ]]
then
  inotifywait -rqe modify "$PWD" | sed -rn 's_^.*\.(.*)$_\1_p' > "$commfile"
else
  inotifywait -qe modify "$PWD" | sed -rn 's_^.*\.(.*)$_\1_p' > "$commfile"
fi
